apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        resources:
          limits:
            memory: "64Mi"
            cpu: "50m"
        env:
        - name: "VERSION"
          value: "1.0.0"
        - name: "ENVIRONMENT"
          value: "dev"
        ports:
        - containerPort: 80
