apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-claim-001
  namespace: app
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 2Gi
