apiVersion: v1
kind: Service
metadata:
  name: php-apache-service
spec:
  selector:
    app: php-apache
  type: ClusterIP
  ports:
    - name: php-apache
      protocol: TCP
      port: 80
      targetPort: 80
