apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      restartPolicy: Always
      volumes:
      - name: pv-storage
        persistentVolumeClaim:
          claimName: pvc-claim-001
      - name: config-volume
        configMap:
          name: nginx-config
      - name: secret-volume
        secret:
          secretName: nginx-secret
      containers:
      - name: nginx
        image: nginx:alpine
        volumeMounts:
        - name: pv-storage
          mountPath: /var/www/html/
        - name: config-volume
          mountPath: /etc/nginx/conf.d/
        - name: secret-volume
          mountPath: /etc/nginx/secrets/
          readOnly: true
        ports:
        - containerPort: 80
        env:
        - name: "ENVIRONMENT"
          value: "dev"
